dist: bionic


language: python
arch:
  - amd64
  - ppc64le

branches:
  only:
    - master


matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=mypy


before_install:
  - sudo apt-get install -y tox


script:
  - tox
